---
title: "Exploratory Data Analysis"
date: "2022-11-23"
output: 
    github_document:
      df_print: kable
---

```{r}
# load libraries
pacman::p_load(
  tidyverse,
  DataExplorer,
  dlookr,
  SmartEDA,
  forecast,
  prettydoc,
  Hmisc,
  ggthemes,
  gapminder,
  ranger
)


```


# EDA report
```{r}
# create report for all variables
create_report(
  gapminder, 
  output_format = "html_document",
  output_file = "gapminder_EDA_report1.html"
  )


# create report with a response variable
create_report(
  gapminder, 
  y = "lifeExp", 
  output_format = "html_document",
  output_file = "gapminder_EDA_report2.html"
  )
```

```{r}
# smart EDA report
ExpReport(
  gapminder,
  op_file = "gapminder_EDA_report3.html"
  )

# diagnose report
diagnose_web_report(
  gapminder,
  output_format = "html",
  output_file = "gapminder_EDA_report4.html"
  )

# eda_report
gapminder %>% 
  eda_web_report(
    target = "lifeExp",
    output_format = "html",
    output_file = "gapminder_EDA_report5.html",
  )

# Airquality transformation report
transformation_web_report(
  datasets::airquality,
  output_file = "gapminder_EDA_report6.html"
)
```





```{r}
diamonds %>% 
  diagnose_web_report(
    output_file = "diamondsreport.html",
    title = "Diamonds Diagnosis Report",
    subtitle = "Source::ggplot2",
    author = "George Ngugi",
    create_date = format(Sys.Date(), "%d %b, %Y"),
    theme = "blue"
  )

```


```{r}
install.packages("nycflights13")
library(nycflights13)

flights %>% 
  diagnose_web_report(
    output_file = "flights.html",
    title = "Nycflights Report",
    author = "George Ngugi",
    create_date = format(Sys.Date(), "%d %b, %Y"),
    theme = "blue"
  )
```


```{r}
flights %>% 
  diagnose_paged_report(
    output_format = "pdf",
    output_dir = "./",
    output_file = "flights.pdf",
    title = "Nycflights Report",
    author = "George Ngugi",
    create_date = format(Sys.Date(), "%d %b, %Y"),
    theme = "blue"
  )
```


```{r}
marketing <- read_csv("datasets/marketing.csv",
                      show_col_types = F) %>% 
  janitor::clean_names()


marketing %>% 
  eda_web_report(
    output_dir = "./",
    output_file = "MarketingEDA.html",
    title = "Marketing EDA Report",
    theme = "blue"
  )
```



```{r}
diamonds %>% 
  transformation_paged_report(
    #target = "price",
    output_format = "pdf",
    output_file = "diamondsT.pdf",
    output_dir = "./",
    title = "Diamonds Transformation Report"
  )
```


```{r}
marketing <- marketing %>% drop_na()

ExpReport(marketing, op_file = "diam.html")

create_report(
  diamonds, 
  output_file = "diam.html", 
  report_title = "Diamonds EDA Report"
  )
```







