---
output: stevetemplates::cv
geometry: margin=.5in

title: "CV"
author: George Ngugi Mwangi

jobtitle: "Data Analyst"
address: "Gatundu Town · Kiambu County · Kenya"
fontawesome: yes
email: mwangigeorge648@gmail.com
github: mwangi-george
linkedin: georgemwangikenya
#osf: "Enter 5 digit osf string here"
phone: "+254 748 177 880"
web: georgengugi.netlify.app/
updated: FALSE
rdateformat: "`r format(Sys.time(), '%d %b %Y')`"

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Summary

An extremely committed analyst with a great deal of passion for interpreting, analyzing, and reconciling data from a variety of sources; competent in developing and improving current processes and methods to fulfill both internal and external analysis needs;
proficient with the current analytical tools, various presentation software, and possesses strong and effective communication skills crucial in conveying outcomes in analysis and investigations conducted; has a strong commitment to meeting deadlines while maintaining accuracy and the highest standard of work.

# Employment

**Stats Growth Ltd.**

Data Collection Officer (Kiambu County) \hfill Feb 2022 - March 2022

Duties: Conducted opinion polls, analyzed data and presented Survey Results



**Kenya National Bureau of Statistics**

Enumerator (Kiambu County) \hfill August 2019

Duties: Conducted interviews and collected demographic data using Computer-Assisted Personal Interviewing.

# Education

*Kenyatta University*, B.Sc. Economics and Statistics (First Class Honours) \hfill 2018 - 2022

*Coursera*, Google Data Analytics Professional Certificate \hfill August 2022 - Present

*Ituru High School*, Kenya Certificate of Secondary Education(Grade B+) \hfill 2014-2017


# Skills

Data Cleaning and Manipulation with R

Parametric Analysis and Hypothesis Testing with R

Sampling Techniques (*Probability Sampling in R*)

Data Visualization (*Excel, Ggplot2, Ms Power BI*)

SQL (*Data Manipulation Language*)

Collaborating (*GitHub*)

Reporting (*R Markdown*)

# Certifications

Foundations Data (*Part of Google Data Analytics Professional Certificate*)

Statement of Accomplishment (*Data Visualization with ggplot2 *)


# References

**Mr Samuel Githae Kinyua**

Economic Analyst at National Treasury &

Part-Time Lecturer at Kenyatta University

Tel: +254 720 108 804

Email: kinyua.samuel@ku.ac.ke



**Timothy Kamau Njicha**

Teacher - Ndundu Secondary School

Tel: +254 720 930 767

Email: timothynjicha@gmail.com
