---
title: "word cloud"
author: "Mwangi George"
date: "2022-11-29"
output: github_document
---

```{r}
options(scipen = 999)
#install.packages("ggwordcloud")

pacman::p_load(
  tidyverse,
  ggwordcloud,
  rtweet,
  data.table,
  tidytext
)

# tweets <- search_tweets(
#   q = "MachakosCountyExposed",
#   n = 500,
#   include_rts = F,
#   retryonratelimit = F
# )
# 
# #str(tweets)

machakos <- read_csv("datasets/machakos.csv", 
                     show_col_types = F)

# unnest machakos
machakos_new <- unnest_tokens(
  tbl = machakos, 
  input = text,
  output = word
)

# get stop words
stp_words <- get_stopwords(
  source = "smart"
)

# remove stop words from machakos_new
machakos_new <- machakos_new %>% 
  anti_join(stp_words, by = "word")

# remove unnecessary numbers
machakos_new <- machakos_new %>% 
  filter(!str_detect(word, "[0-9]"))
```

```{r fig.align='center', fig.height=7, fig.width=10}
machakos_new %>% 
  mutate(
    word = as.factor(word),
    word = fct_lump_n(word, n = 15)
  ) %>% 
  filter(!word %in% c("Other", "t.co")) %>% 
  add_count(word) %>% 
  ggplot(
    aes(
      x = fct_reorder(word, n)
    )
  )+
  geom_bar(fill = "#2171B5", alpha = .6)+
  coord_flip()+
  labs(
    title = "Top Trending Texts in Kenya",
    subtitle = "Based on the hashtag #MachakosCountyExposed exclusive of retweets",
    caption = "Data Source: Twitter API",
    x = ""
  )+
  ggthemes::theme_few()+
  theme(
    plot.background = element_rect(fill = "gray90"),
    panel.background = element_rect(fill = "gray96"),
    axis.text = element_text(size = 13),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(size = 12),
    plot.subtitle = element_text(size = 12)
  )

```

```{r}
machakos %>% 
  ggplot(
    aes(
      created_at, favorite_count
    )
  )+
  geom_line()


machakos %>% 
  filter(favorite_count > 10) %>% 
  ggplot(aes(created_at, favorite_count))+
  geom_line()

machakos %>% 
  #slice_max(favorite_count, n = 10) %>% 
  ggplot(aes((favorite_count), (retweet_count)))+
  geom_jitter()+
  scale_x_log10()+
  scale_y_log10()

machakos %>% 
  #slice_sample(n = 100) %>% 
  summarise(cor_likes_retweets = cor(favorite_count, retweet_count),
            avg_text_length = mean(str_length(text)),
            avg_likes = mean(favorite_count),
            avg_retweets = mean(retweet_count))

machakos %>% 
  filter(!favorite_count > 300 & !favorite_count < 10) %>% 

  ggplot(
    aes(
      x = " ", y = favorite_count
    )
  )+
  geom_boxplot()
```





















